const AppErrorCode = Object.freeze({
    InvalidAccessToken: "InvalidAccessToken",
    MissingRole: "MissingRole",
    InvalidRole: "InvalidRole",
    MissingUserId: "MissingUserId",
    InvalidUserId: "InvalidUserId",
    MissingSessionId: "MissingSessionId",
    InvalidSessionId: "InvalidSessionId",
    MissingRefreshToken: "MissingRefreshToken",
    InvalidRefreshToken: "InvalidRefreshToken",
    MissingPassword: "MissingPassword",
    InsufficientPermission: "InsufficientPermission",
    UserNotFound: "UserNotFound",
    AccountSuspended: "AccountSuspended",
    AccountNotApproved: "AccountNotApproved",
    EmailAlreadyExists: "EmailAlreadyExists",
    InvalidEmail: "InvalidEmail",
    WeakPassword: "WeakPassword",
    TokenExpired: "TokenExpired",
    ActionNotAllowed: "ActionNotAllowed",
    DatabaseError: "DatabaseError",
    ValidationError: "ValidationError",
    RateLimitExceeded: "RateLimitExceeded",
    FileTooLarge: "FileTooLarge",
    UnsupportedFileType: "UnsupportedFileType",
    MissingFields: "MissingFields",
    OperationFailed: "OperationFailed",
    ServiceUnavailable: "ServiceUnavailable",
});

module.exports = AppErrorCode
